version: "3"

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mainDB
    ports:
      - "5432:5432"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6


networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
    