version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: npm run dev

   

    