name: Trigger auto deployment for tts-container-crnd

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/tts-container-crnd-AutoDeployTrigger-4b171390-a7d0-47e9-8be6-6dde03ad2db1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: telemessage.azurecr.io
          username: ${{ secrets.TTSCONTAINERCRND_REGISTRY_USERNAME }}
          password: ${{ secrets.TTSCONTAINERCRND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: telemessage.azurecr.io/tts-container-crnd:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TTSCONTAINERCRND_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n tts-container-crnd -g Telemessage-ACA-crnd --server telemessage.azurecr.io --username  ${{ secrets.TTSCONTAINERCRND_REGISTRY_USERNAME }} --password ${{ secrets.TTSCONTAINERCRND_REGISTRY_PASSWORD }}
            az containerapp update -n tts-container-crnd -g Telemessage-ACA-crnd --image telemessage.azurecr.io/tts-container-crnd:${{ github.sha }}
